# Generated by Django 4.1.7 on 2023-02-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('book_title', models.TextField(max_length=100)),
                ('book_cover_front', models.FileField(upload_to='books')),
                ('book_cover_back', models.FileField(upload_to='books')),
                ('book_sample', models.FileField(upload_to='books')),
                ('book_author1', models.TextField(max_length=50)),
                ('book_author2', models.TextField(max_length=50, null=True)),
                ('book_publisher', models.TextField(max_length=100, null=True)),
                ('buy_link1', models.URLField(max_length=255)),
                ('buy_link2', models.URLField(max_length=255)),
            ],
        ),
    ]
